### ISSUE TITLE
update docs

### ISSUE THREAD

**Issue by bdarcus** [Zaeph/org-roam-bibtex#1]
Great to see this!

I know the transition is still in process (you need to update the instructions at top of the el file, and incorporate them into the readme, for example), but can you let me know when ready to test, and you are looking for feedback?

**Comment by Zaeph** [comment]
Thanks for offering your help!

The package is working right now, and I don't have the time right now to work on the `README.md`.  If you want to try it out, clone the repo, and add the following to your config:

```el
(use-package org-roam-bibtex
  :load-path "~/projects/org-roam-bibtex/" ;Edit with the path to the repo
  :config
  ;; Enable a global minor-mode to shadow the edit-note action
  (org-roam-bibtex))
```

Then, if you run `helm-bibtex` or `ivy-bibtex` and run the action to edit the note, it should find or create the note in your `org-roam-directory`.

**Comment by Zaeph** [comment]
Well, actually, something seems to be borked, since notes which have already been created are opened in an `org-capture` buffer. 🤔

…Guess it's still very rough around the edges.  I'll let you know when it's functional!

**Comment by bdarcus** [comment]
Sounds good. 

I successfully installed it using doom package!, which is a wrapper for straight, like so:

``` elisp
(package! org-roam-bibtex :recipe
  (:host github :repo "Zaeph/org-roam-bibtex"))
```

I'll pause on the config and testing though!

**Comment by Zaeph** [comment]
Good!

> Well, actually, something seems to be borked, since notes which have already been created are opened in an `org-capture` buffer.

Fixed in 1fcee8a!

I've also made `org-ref`'s `Edit note` action work with the modifications I've made.

You should be able to test the package now.  The default config creates notes in your `org-roam-directory` formatted as `<citekey>.org`.  Try it on one of your entries in `helm-bibtex` or `ivy-bibtex`, and it should work.

**Comment by bdarcus** [comment]
It does indeed work, and does indeed use the default org-roam-directory.

But I want to use my org-ref-notes-directory, which I have as a subdir of my roam directory.

Thoughts?

**Comment by Zaeph** [comment]
> It does indeed work, and does indeed use the default org-roam-directory.

Good!

> But I want to use my org-ref-notes-directory, which I have as a subdir of my roam directory.
> 
> Thoughts?

There's a slight problem here.  I've coded it so you can customize `org-roam-bibtex-template` which works exactly like `org-roam-capture-templates`, but I've based my work off jethrokuan/org-roam#427 which allows you to define subdirectories with `:file-name "subdir/${slug}".  I think the PR will be merged soon, but until then, I'd rather hold off on other means of customisation.

**Comment by bdarcus** [comment]
No problem.

**Comment by bdarcus** [comment]
Readme is looking good.

**Comment by bdarcus** [comment]
Just a quick question, though: one doesn't actually need to define the `org-roam-bibtex-template` in the use-package config; right? There is a default template?

If I understand correctly, you might mention that, since will simplify things for emacs newbies.

**Comment by Zaeph** [comment]
> Just a quick question, though: one doesn't actually need to define the `org-roam-bibtex-template` in the use-package config; right? There is a default template?

Yes, there is:
https://github.com/Zaeph/org-roam-bibtex/blob/a1729172b98aa3d76fdae69a07b185a4b824bfa7/org-roam-bibtex.el#L78

I’ve still got to write a section in the `README.md` for customisable commands.  I’ll get to it soon, thanks for highlighting it!

**Comment by bdarcus** [comment]
Perfect; you can flag the "simple" config with the default in the general section, and then the "if you want a custom template then ..." in that new section.

**Comment by Zaeph** [comment]
All right, I think we've got a pretty decent `README.md` now.  I've written the [Quick-start](https://github.com/Zaeph/org-roam-bibtex#quick-start) part of the guide as a newbie-friendly section, as well as the description of [`org-roam-bibtex-template`](https://github.com/Zaeph/org-roam-bibtex#org-roam-bibtex-template).  The more advanced [`org-roam-bibtex-preformat-keywords`](https://github.com/Zaeph/org-roam-bibtex#org-roam-bibtex-preformat-keywords) copies the docstring.

**Comment by bdarcus** [comment]
Perfect!
