### ISSUE TITLE
minor suggestion on git commits, history

### ISSUE THREAD

**Issue by bdarcus** [Zaeph/org-roam-bibtex#12]
Having just learned a bit about this myself, it occurs to me you might look into git rebase to consolidate some of the commits into a cleaner history.

Much of this could be rebased into a single "update docs ..." commit, for example.

![Screenshot from 2020-04-19 13-12-19](https://user-images.githubusercontent.com/1134/79694648-ab7f0400-823f-11ea-8b3b-4abae3ca24c1.png)

This will likely become more important as the package gets released on MELPA, and more people are using it?

**Comment by Zaeph** [comment]
> Having just learned a bit about this myself, it occurs to me you might look into git rebase to consolidate some of the commits into a cleaner history.

This is a matter of religion. 🤡

I do minimal commits, and I try to make the steps as obvious as possible.  I also prefer to  `--no-fast-forward` merging to make the work a little more obvious.  I do agree that the number of commits for `README.md` has gone a little overboard, though, and I'll rebase those in the future.

> This will likely become more important as the package gets released on MELPA, and more people are using it?

I don't think this would be a problem: MELPA will just point to the latest commit on `master`.
