### ISSUE TITLE
Packaging of dependencies

### ISSUE THREAD

**Issue by tmalsburg** [Zaeph/org-roam-bibtex#2]
I factorered out bibtex-completion from helm-bibtex when ivy became a thing but never made it its own package as there was not really a need for that.  Do I understand correctly that org-roam-bibtex would benefit from a separate bibtex-completion package?  This could easily be done if necessary.

**Comment by Zaeph** [comment]
Yes, it would be nice to separate `bibtex-completion` from `helm-bibtex` and `ivy-bibtex`.

The problem with the legacy name of `helm-bibtex` is that [people assume that `ivy-bibtex` is not supported](https://github.com/jethrokuan/org-roam/issues/423#issuecomment-612021066), even though we're only using `bibtex-completion.el`.

**Comment by tmalsburg** [comment]
> The problem with the legacy name of helm-bibtex is that people assume that ivy-bibtex is not supported, even though we're only using bibtex-completion.el.

Yes, that impression is easy to get.  Will make it a separate package then.

**Comment by tmalsburg** [comment]
Here we go: https://github.com/melpa/melpa/pull/6840

**Comment by Zaeph** [comment]
> Here we go: [melpa/melpa#6840](https://github.com/melpa/melpa/pull/6840)

Splendid, thanks for the split and the PR!

**Comment by tmalsburg** [comment]
I think this can be closed.
