### ISSUE TITLE
Shorter prefix for org-roam-bibtex

### ISSUE THREAD

**Issue by myshevchuk** [zaeph/org-roam-bibtex#23]
@zaeph I find the symbol names tend to become increasingly cumbersome as new functionality is added, such as note actions.

I'm now staring at newly invented `org-roam-bibtex-note-actions-noter-heading-format` variable and do not like it at all.

My suggestion here is to keep `org-roam-bibtex` namespace prefix for the main library `org-roam-bibtex.el` and to abbreviate it to `orb` for `org-roam-bibtex-note-actions.el` and any new libraries yet to come.

**Comment by zaeph** [comment]
That seems like a reasonable thing to do.

I'm not sure if there are rules to be followed on that front, but I have no problem with it.  Would you mind taking care of it?

**Comment by myshevchuk** [comment]
I don't think there are any specific rules, except that it is a good practice to prefix top level definitions with the name of the library. What holds me back in our situation is the example of `smartparens` package, which has seemingly random `smartparens` and `sp` prefixes (they are probably not random, but look so).

Org-mode, on the other hand, has an opposite situation:
> org-latex-export-block is a compiled function defined in ox-latex.el.

They have short names for libraries and full names for definitions. And the example above is also a mess actually, it should have been `org-export-latex-block`.

So definitely no one will point fingers at us. On the other hand, it may create confusion, for ourselves including.

Renaming the whole package to `orb` is appealing to me with the word play `org` - `orb` and that orb is an actual word, like in Orb of Knowledge (I'm not a native English speaker and for me "orb" is one of those, you know, cool-sounding words you can find in any language). But that makes these two names too similar besides the fact that `g` and `b` are typed with the same finger on the keyboard and will definitely be a cause for many typos.

**Comment by zaeph** [comment]
> Renaming the whole package to `orb` is appealing to me with the word play `org` - `orb` and that orb is an actual word, like in Orb of Knowledge (I'm not a native English speaker and for me "orb" is one of those, you know, cool-sounding words you can find in any language). But that makes these two names too similar besides the fact that `g` and `b` are typed with the same finger on the keyboard and will definitely be a cause for many typos.

Fun fact: the [logo for the project](https://github.com/zaeph/org-roam-bibtex#org-roam-bibtex) was actually designed with the idea of an orb in mind, hence the sphere in the background!

<img src="https://raw.githubusercontent.com/zaeph/org-roam-bibtex/master/doc/logo-r500.png" width="150">

Personally, I wouldn't be opposed to keeping the name of the library as `org-roam-bibtex` to maintain discoverability from Org-roam, but to change the prefix to `orb` in the entire project, including those in `org-roam-bibtex.el`.  Think of all the characters we'd save! 🤡

**Comment by myshevchuk** [comment]
Ok, then agreed.

**Comment by myshevchuk** [comment]
I'll do it later tonight.

**Comment by myshevchuk** [comment]
We can play with uppercase and make it, for example, `OrB-` to pun at `TeX` and friends. It's less convenient to type, but will lead to less typos.

**Comment by myshevchuk** [comment]
```
OrB-mode
OrB-note-actions
OrB-find-non-ref-file
OrB-edit-notes
...
```

**Comment by zaeph** [comment]
> We can play with uppercase and make it, for example, `OrB-` to pun on `TeX` and friends. It's less convenient to type, but will lead to less typos.

Oof, not a fan of that.  If we go that way, in 10 years, we'll be as anal-retentive as some of the hardcore TeXnicians about properly capitalising the word.  I think `orb` is fine, really.
