### ISSUE TITLE
Cannot use :head (concat ...) in org-roam-bibtex-template

### ISSUE THREAD

**Issue by tdehaeze** [Zaeph/org-roam-bibtex#6]
Hi,

First of all, thanks for this package. It works wonderfully for me :)

I would like to use `concat` for make the `:head` part of `org-roam-bibtex-template` more readable as shown below.

```
  (setq org-roam-bibtex-template
        '(("r" "ref" plain (function org-roam-capture--get-point) ""
           :file-name "${=key=}"
           :head (concat "#+TITLE: ${=key=}: ${title}\n"
                         "#+ROAM_KEY: ${ref}\n"
                         "- tags ::\n"
           :unnarrowed t)))
```

When I do so, I have the following error:
```
replace-regexp-in-string("\\${=key=}" "schulte12_multi_languag_comput_envir_liter" (concat "#+TITLE: ${=key=}: ${title}") t t)
```

It seems it does not "expand" the `concat` before doing the regex.
I am an elisp-beginner so I guess I did something stupid...

**Comment by tdehaeze** [comment]
Ok, I could figure it out, so instead of deleting the issue, I post the answer I found here: https://emacs.stackexchange.com/questions/38757/cannot-use-concat-within-org-capture-template

The correct way to do it is:
```
  (setq org-roam-bibtex-template
        `(("r" "ref" plain (function org-roam-capture--get-point) ""
           :file-name "${=key=}"
           :head ,(concat "#+TITLE: ${=key=}: ${title}\n"
                         "#+ROAM_KEY: ${ref}\n"
                         "- tags ::\n"
           :unnarrowed t)))
```

Note the backquote =`= and the =,=.

**Comment by Zaeph** [comment]
> First of all, thanks for this package. It works wonderfully for me :)

Glad you're liking it!



> The correct way to do it is:
> 
> ```
>   (setq org-roam-bibtex-template
>         `(("r" "ref" plain (function org-roam-capture--get-point) ""
>            :file-name "${=key=}"
>            :head ,(concat "#+TITLE: ${=key=}: ${title}\n"
>                          "#+ROAM_KEY: ${ref}\n"
>                          "- tags ::\n"
>            :unnarrowed t)))
> ```
> 
> Note the backquote =`= and the =,=.

You don't actually need to do that.  Compare:
```el
(setq org-roam-bibtex-template
      '(("r" "ref" plain (function org-roam-capture--get-point) ""
         :file-name "${=key=}"
         :head "#+TITLE: ${=key=}: ${title}\n#+ROAM_KEY: ${ref}\n- tags ::\n"
         :unnarrowed t)))
```
`:head` accepts a string a string argument, not a sexp that *returns* a string argument.  Your original solution works, yes, but here, you can just manually concatenate the string by joining all the parts.

**Comment by tdehaeze** [comment]
Thanks for the tip, but I actually plan to have quite large template like:
```
  (setq org-roam-bibtex-template
        `(("r" "ref" plain (function org-roam-capture--get-point) ""
           :file-name "${=key=}"
           :head ,(concat "#+TITLE: ${=key=}: ${title}\n"
                          "#+ROAM_KEY: ${ref}\n"
                          "- Tags :: %?\n"
                          "- Author(s) :: ${author}\n"
                          "- Year :: ${year}\n"
                          "\n"
                          "* Notes                                                               :ignore:\n"
                          ":PROPERTIES:\n"
                          ":NOTER_DOCUMENT: ../pdfs/${=key=}.pdf\n"
                          ":END:\n")
           :unnarrowed t)))
```

Which would be quite unreadable without the `concat` in my opinion.

**Comment by Zaeph** [comment]
I agree that it'd get unwieldy quite quickly.  I only mentioned this because it saves a few keystrokes and saves an eval, but since it's only a `setq` assignment for your config, it's a-OK. 👍

**Comment by Zaeph** [comment]
> Thanks for the tip, but I actually plan to have quite large template like:

You might be interested in [using a file-template](https://github.com/Zaeph/org-roam-bibtex/issues/10#issuecomment-615195696) as explaind in #10.

**Comment by tdehaeze** [comment]
> > Thanks for the tip, but I actually plan to have quite large template like:
> 
> You might be interested in [using a file-template](https://github.com/Zaeph/org-roam-bibtex/issues/10#issuecomment-615195696) as explained in #10.

Thanks! I was not aware of this very nice option :).
